### ISSUE TITLE
Does not work with Sass interpolation

### ISSUE THREAD

**Issue by ruedap** [postcss/postcss-bem-linter#132]
This plugin does not seem to support [Sass interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_).

## input.scss:

```scss
/** @define ComponentName */
.ComponentName {
  $ComponentName: &;

  &--modifierName {
    color: blue;

    #{$ComponentName} {  // <- Sass interpolation
      &-decendantName {
        color: red;
      }
    }
  }
}
```

### postcss-bem-linter result:

```
input.scss
 9:7  ✖  Invalid component selector                   plugin/selector-bem-pattern
         ".ComponentName--modifierName
         #{$ComponentName}-decendantName"
```

## output.css

```css
/** @define ComponentName */
.ComponentName--modifierName {
  color: blue;
}
.ComponentName--modifierName .ComponentName-decendantName {
  color: red;
}

```

### postcss-bem-linter result:

No errors
