### ISSUE TITLE
Concise & verbose comment syntax for "weak" not fully working?

### ISSUE THREAD

**Issue by fabd** [postcss/postcss-bem-linter#144]
In the following simple test case, the "weak" option doesn't seem to work with the verbose comment:

**No eslint warning**:

```
/** @define VuePage; weak */
.VuePage { 
  background: #f8f8f8;

  h3 {
    color: red;
  }
}
```

**1 eslint warning**: "Invalid component selector ".VuePage h3"

```
/* postcss-bem-linter: define VuePage; weak */
.VuePage { 
  background: #f8f8f8;

  h3 {
    color: red;
  }
}
```

Have I misconfigured something?

Also I understand it's not good practice, but it seems fairly essential to be able to add simple elements such as h3, p etc. For example to add default styles to a Card component's body text. Is there a way to enable these while keeping the linting?

**Comment by Didel** [comment]
**+1**

I noticed the exact same thing. Using`; weak` with verbose syntax does not seem to work, using it with concise syntax works fine. I am using version 3.3.0 of postcss-bem-linter.

❌ **Throws Invalid component selector ".tab-content .tab-pane" :**
```SCSS
/** postcss-bem-linter: define tab-content; weak */
.tab-content .tab-pane {
  margin-bottom: 0;
}
```

✅ **Passes fine: **
```SCSS
/** @define tab-content; weak */
.tab-content .tab-pane {
  margin-bottom: 0;
}
```

I also agree with @fabd above, having a shorthand option for ignore (e.g. `@ignore` ) would be a nice addition!
