### ISSUE TITLE
Allow opting out on a per rule basis

### ISSUE THREAD

**Issue by simonsmith** [postcss/postcss-bem-linter#47]
I think it would be useful to tell bemlint to skip a rule if needed:

``` css
/* bemlint ignore:rule */
.no-flexbox .Component {
  display: block;
}
```

For me the use case is when I need to add some Modernizr fallbacks to a component and have to end up opting out of linting entirely to allow it to work. Moving the rules into a separate file also feels wrong.
