### ISSUE TITLE
Support for CSS @apply Rule

### ISSUE THREAD

**Issue by JosefJezek** [postcss/postcss-bem-linter#64]
Could you add support for CSS `@apply` Rule?

- http://tabatkins.github.io/specs/css-apply-rule/
- https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins
- https://github.com/StartPolymer/polymer-starter-kit-plus

```css
.Navigation {
  --paper-menu-selected-item: {
    color: var(--default-primary-color);
  };
}
```
-> `Invalid component selector ".Navigation --paper-menu-selected-item:" [postcss-bem-linter]`
