### ISSUE TITLE
Cannot ignore custom property name

### ISSUE THREAD

**Issue by jgautheron** [postcss/postcss-bem-linter#74]
Custom component selectors can be ignored but custom property names **cannot**.

Quick example:

```css
.Navigation {
  /* postcss-bem-linter: ignore */
  --paper-menu-selected-item: {
    color: #262626;
  };

  /* postcss-bem-linter: ignore */
  --paper-menu-background-color: #fff;
}
```

`11:3	⚠  Invalid custom property name "--paper-menu-background-color": a component's custom properties must start with the component name [postcss-bem-linter]`

The first is properly ignored, the second is not.
Is there any other way to ignore custom property names?
