### ISSUE TITLE
does not work with SASS mixins and ampersand selector

### ISSUE THREAD

**Issue by AndyOGo** [postcss/postcss-bem-linter#97]
The following code incorrectly lints: `Invalid component selector "&:hover"`

````scss
@mixin link {
  color: blue;

  &:hover {
    color: red;
  }
}

.link {
  @include link();
}
````

**Note**
With declarative style of `Less` this is not a problem.
